# php.yml 
--- 
- hosts: dev 
  become: True 
  tasks: 
   - name: Make sure Apache LATEST version installed
     apt:
      name: apache2
      state: present

   - name: Make sure Apache is Running
     service:
      name: apache2
      state: started
  
    - name: Deploy static website 
      copy: 
       src: index.php # We have define a html page 
       dest: /var/www/html/
