# php.yml 
--- 
- hosts: dev 
  become: True 
  tasks: 
   
    - name: Deploy static website 
      copy: 
       src: login.php # We have define a html page 
       dest: /var/www/html/

    - name: Deploy member webpage
      copy: 
       src: members_panel.php # We have define a html page 
       dest: /var/www/html/
